CREATE TABLE PERSON (
  ID      INTEGER     NOT NULL,
  NAME    VARCHAR(25) NOT NULL,
  ADDRESS VARCHAR(25) NOT NULL,
  ZIP     VARCHAR(25) NOT NULL,
  PRIMARY KEY (NAME)
);

CREATE TABLE HOTEL (
  ID      INTEGER     NOT NULL,
  NAME    VARCHAR(25) NOT NULL,
  ADDRESS VARCHAR(25) NOT NULL,
  ZIP     VARCHAR(25) NOT NULL,
  PRIMARY KEY (NAME)
);
